language: node_js
node_js:
- "node"
addons:
  apt:
    packages:
    - libgconf-2-4
cache:
  npm: true
  directories:
    - ~/.cache
install:
  - npm ci
before_script:
  - npm test && npm run dev && sleep 10 &
script:
  - $(npm bin)/cypress run --parallel
